import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test, { after, before } from "node:test";
import { PDFDict, PDFDocument, PDFName } from "pdf-lib";
import sharp from "sharp";
import {
  decodedSmtpText,
  smtpAttachmentNames,
  startTestServer
} from "../helpers/test-server.mjs";

let app;
let adminCookie;

before(async () => {
  app = await startTestServer({ inProcess: true });
  adminCookie = await app.login("admin@example.com", "Admin123!");
  await app.cacheCsrf("/admin", adminCookie);
});

after(async () => {
  await app?.stop();
});

test("invoice template, draft, selected columns, calculations, PDF, email, and public view work end to end", async () => {
  const templateUpdate = await app.postForm(
    "/admin/checks/template",
    {
      academyName: "Maritime Portal Test Academy",
      academySubtitle: "International maritime education",
      address: "1 Test Harbour",
      contacts: "info@maritimeportal.test",
      iban: "TEST-IBAN-001",
      paymentDetails: "Training services",
      beneficiaryBank: "Test Beneficiary Bank",
      correspondentBank: "Test Correspondent Bank",
      directorName: "Test Director",
      accountantName: "Test Accountant",
      footerNote: "Generated by the automated test suite"
    },
    adminCookie
  );
  assert.equal(templateUpdate.response.status, 303);
  assert.equal(templateUpdate.response.headers.get("location"), "/admin/checks/template");

  const filterQuery = new URLSearchParams();
  for (const column of ["student", "email", "course", "assignedAt", "status", "amount"]) {
    filterQuery.append("column", column);
  }
  const create = await app.postForm(
    "/admin/checks/invoices/create",
    {
      filterQuery: filterQuery.toString(),
      assignmentId: "assign_demo",
      recipientName: "Bluewater Training Manager",
      recipientEmail: "billing@example.com",
      recipientCompany: "Bluewater Crew"
    },
    adminCookie
  );
  assert.equal(create.response.status, 303);
  const invoiceLocation = create.response.headers.get("location");
  assert.match(invoiceLocation, /^\/admin\/checks\/invoices\/invoice_/);
  const invoiceId = invoiceLocation.split("/").at(-1);

  await app.waitFor(
    () => app.readDb().settings.invoices?.some((invoice) => invoice.id === invoiceId),
    "Invoice draft was not persisted."
  );
  let invoice = app.readDb().settings.invoices.find((item) => item.id === invoiceId);
  assert.equal(invoice.status, "draft");
  assert.equal(invoice.lines.length, 1);
  assert.equal(invoice.lines[0].assignmentId, "assign_demo");
  assert.deepEqual(invoice.columns, ["student", "email", "course", "assignedAt", "status", "amount"]);
  assert.ok(existsSync(`${app.uploadsDir}/invoices/${invoiceId}.pdf`));

  const line = invoice.lines[0];
  const update = await app.postForm(
    `/admin/checks/invoices/${invoiceId}/update`,
    {
      recipientName: "Bluewater Accounts",
      recipientCompany: "Bluewater Crew",
      recipientEmail: "billing@example.com",
      issueDate: "2026-07-23",
      dueDate: "2026-08-22",
      currency: "USD",
      comment: "Monthly maritime training invoice",
      paidAt: "",
      discount: "10",
      extraCharge: "5",
      vatRate: "20",
      status: "issued",
      column: ["student", "course", "amount"],
      [`included_${line.id}`]: "on",
      [`amount_${line.id}`]: "100",
      [`lineDiscount_${line.id}`]: "15",
      sendEmail: "1"
    },
    adminCookie
  );
  assert.equal(update.response.status, 303);
  assert.equal(update.response.headers.get("location"), invoiceLocation);

  await app.waitFor(
    () => app.readDb().settings.invoices.find((item) => item.id === invoiceId)?.status === "sent",
    "Invoice update was not persisted."
  );
  invoice = app.readDb().settings.invoices.find((item) => item.id === invoiceId);
  assert.equal(invoice.recipientName, "Bluewater Accounts");
  assert.equal(invoice.status, "sent");
  assert.equal(invoice.lines[0].amount, 100);
  assert.equal(invoice.lines[0].discount, 15);
  assert.equal(invoice.discount, 10);
  assert.equal(invoice.extraCharge, 5);
  assert.equal(invoice.vatRate, 20);
  assert.ok(invoice.changes.some((change) => change.action.includes("sent by email")));

  const detail = await app.request(invoiceLocation, { headers: { cookie: adminCookie } });
  assert.equal(detail.response.status, 200);
  assert.match(detail.text, /Bluewater Accounts/);
  assert.match(detail.text, /Monthly maritime training invoice/);
  assert.match(detail.text, /96\.00|96 USD/);

  const pdfResponse = await app.request(`/admin/checks/invoices/${invoiceId}.pdf`, {
    headers: { cookie: adminCookie }
  });
  assert.equal(pdfResponse.response.status, 200);
  assert.equal(pdfResponse.response.headers.get("content-type"), "application/pdf");
  assert.match(pdfResponse.response.headers.get("content-disposition"), /attachment/);
  assert.ok(pdfResponse.body.length > 1500);
  const invoicePdf = await PDFDocument.load(pdfResponse.body);
  assert.equal(invoicePdf.getPageCount(), 1);
  const invoicePage = invoicePdf.getPage(0);
  assert.ok(Math.abs(invoicePage.getWidth() - 595.28) < 2);
  assert.ok(Math.abs(invoicePage.getHeight() - 841.89) < 2);

  await app.waitFor(
    () => app.smtp.messages.some((message) => decodedSmtpText(message).includes(invoice.number)),
    "Invoice email was not delivered to the SMTP fixture."
  );
  const invoiceEmail = app.smtp.messages.find((message) => decodedSmtpText(message).includes(invoice.number));
  assert.match(decodedSmtpText(invoiceEmail), /Bluewater Accounts|invoice/i);

  const shared = await app.request(`/invoices/${invoice.id}/${invoice.shareToken}.pdf`);
  assert.equal(shared.response.status, 200);
  assert.equal(shared.response.headers.get("content-type"), "application/pdf");
  await app.waitFor(
    () => app.readDb().settings.invoices.find((item) => item.id === invoiceId)?.status === "viewed",
    "Opening a shared invoice did not mark it as viewed."
  );
  const invalidShared = await app.request(`/invoices/${invoice.id}/invalid-token.pdf`);
  assert.equal(invalidShared.response.status, 404);

  const exportResponse = await app.request(`/admin/checks/export.xls?${filterQuery}`, {
    headers: { cookie: adminCookie }
  });
  assert.equal(exportResponse.response.status, 200);
  assert.match(exportResponse.response.headers.get("content-type"), /excel/);
  assert.match(exportResponse.text, /Student|Course/);
});

test("certificate designer supports A4 background, custom fields, apply-all, backup, restore, and validation", async () => {
  const exportBefore = await app.request(
    "/admin/courses/course_maritime_safety/certificate-designer/export",
    { headers: { cookie: adminCookie } }
  );
  assert.equal(exportBefore.response.status, 200);
  const backupBefore = JSON.parse(exportBefore.text);
  assert.equal(backupBefore.format, "marine-lms-certificate-template");
  assert.equal(backupBefore.version, 1);

  const designer = structuredClone(backupBefore.designer);
  designer.pageWidth = 1123;
  designer.pageHeight = 794;
  designer.fields.push({
    key: "custom_text_test_suite",
    label: "Custom test field",
    text: "Convention \u00a7 157.415 - International \u00abMaritime\u00bb standard\nCrew safety: \u0411\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u044c \u044d\u043a\u0438\u043f\u0430\u0436\u0430",
    x: 12,
    y: 58,
    width: 62,
    height: 14,
    fontSize: 20,
    color: "#06395d",
    fontWeight: 700,
    align: "left",
    visible: true,
    isCustomText: true
  });
  const background = await sharp({
    create: { width: 1123, height: 794, channels: 4, background: { r: 245, g: 250, b: 253, alpha: 1 } }
  }).png().toBuffer();
  const update = await app.postMultipart(
    "/admin/courses/course_maritime_safety/certificate-designer",
    {
      designerJson: JSON.stringify(designer),
      applyToAllCourses: "on"
    },
    {
      backgroundFile: { name: "a4-background.png", type: "image/png", buffer: background }
    },
    adminCookie
  );
  assert.equal(update.response.status, 303);

  const databaseAfterUpdate = app.readDb();
  for (const course of databaseAfterUpdate.courses) {
    const savedDesigner = course.source?.certificateDesigner;
    assert.ok(savedDesigner, `Designer was not applied to ${course.title}.`);
    assert.equal(savedDesigner.pageWidth, 1123);
    assert.equal(savedDesigner.pageHeight, 794);
    assert.ok(savedDesigner.fields.some((field) => field.key === "custom_text_test_suite"));
    assert.match(course.certificateTemplateHtml, /International \u00abMaritime\u00bb standard/);
  }
  assert.ok(databaseAfterUpdate.settings.defaultCertificateDesigner);
  assert.ok(existsSync(`${app.uploadsDir}/${databaseAfterUpdate.courses[0].source.certificateDesigner.backgroundUrl.replace("/uploads/", "")}`));

  const exported = await app.request(
    "/admin/courses/course_maritime_safety/certificate-designer/export",
    { headers: { cookie: adminCookie } }
  );
  const savedBackup = JSON.parse(exported.text);
  assert.ok(savedBackup.designer.fields.some((field) => field.key === "custom_text_test_suite"));

  const reset = await app.postMultipart(
    "/admin/courses/course_maritime_safety/certificate-designer",
    { designerJson: "{}", resetDesigner: "on", removeBackground: "on" },
    {},
    adminCookie
  );
  assert.equal(reset.response.status, 303);
  assert.ok(!app.readDb().courses[0].source.certificateDesigner.fields.some((field) => field.key === "custom_text_test_suite"));

  const restore = await app.postMultipart(
    "/admin/courses/course_maritime_safety/certificate-designer",
    { restoreDesignerBackup: "1" },
    {
      certificateDesignerBackup: {
        name: "certificate-backup.json",
        type: "application/json",
        buffer: Buffer.from(JSON.stringify(savedBackup))
      }
    },
    adminCookie
  );
  assert.equal(restore.response.status, 303);
  assert.ok(app.readDb().courses[0].source.certificateDesigner.fields.some((field) => field.key === "custom_text_test_suite"));

  const invalidRestore = await app.postMultipart(
    "/admin/courses/course_maritime_safety/certificate-designer",
    { restoreDesignerBackup: "1" },
    {
      certificateDesignerBackup: {
        name: "invalid.json",
        type: "application/json",
        buffer: Buffer.from(JSON.stringify({ format: "wrong", version: 1 }))
      }
    },
    adminCookie
  );
  assert.equal(invalidRestore.response.status, 400);
  assert.match(invalidRestore.text, /not a valid Marine LMS certificate template backup/i);
});

test("manual certificate issue creates a unique five-year certificate, A4 PDF, verification page, and email attachment", async () => {
  const photo = await sharp({
    create: { width: 480, height: 640, channels: 3, background: { r: 30, g: 90, b: 120 } }
  }).jpeg().toBuffer();
  const upload = await app.postMultipart(
    "/admin/users/photo",
    { id: "user_student" },
    { photo: { name: "student.jpg", type: "image/jpeg", buffer: photo } },
    adminCookie
  );
  assert.equal(upload.response.status, 303);

  const issue = await app.postForm(
    "/admin/certificates/issue-manual",
    {
      userId: "user_student",
      courseId: "course_first_aid",
      issuedAt: "2026-07-01"
    },
    adminCookie
  );
  assert.equal(issue.response.status, 303);
  assert.equal(issue.response.headers.get("location"), "/admin/certificates?userId=user_student");

  await app.waitFor(
    () => app.readDb().certificates.some((certificate) => certificate.courseId === "course_first_aid"),
    "Manual certificate was not persisted."
  );
  const certificate = app.readDb().certificates.find((item) => item.courseId === "course_first_aid");
  assert.match(certificate.certificateNumber, /^\d{9}\/01\/07\/2026$/);
  assert.equal(certificate.issuedAt.slice(0, 10), "2026-07-01");
  assert.equal(certificate.expiresAt.slice(0, 10), "2031-07-01");
  assert.equal(certificate.status, "issued");

  const pdf = await app.request(`/certificates/${certificate.id}.pdf`, {
    headers: { cookie: adminCookie }
  });
  assert.equal(pdf.response.status, 200);
  assert.equal(pdf.response.headers.get("content-type"), "application/pdf");
  assert.ok(pdf.body.length > 2000);
  const document = await PDFDocument.load(pdf.body);
  assert.equal(document.getPageCount(), 1);
  const page = document.getPage(0);
  const dimensions = [page.getWidth(), page.getHeight()].sort((a, b) => a - b);
  assert.ok(Math.abs(dimensions[0] - 595.28) < 3);
  assert.ok(Math.abs(dimensions[1] - 841.89) < 3);
  const fontResources = page.node.Resources()?.lookup(PDFName.of("Font"), PDFDict);
  assert.ok(fontResources, "Certificate PDF must include font resources.");
  assert.ok(
    fontResources.entries().some(([, reference]) => {
      const font = document.context.lookup(reference, PDFDict);
      return Boolean(font?.get(PDFName.of("ToUnicode")));
    }),
    "Certificate PDF must embed a Unicode font with a ToUnicode map."
  );

  const printablePdf = await app.request(`/certificates/${certificate.id}.pdf?print=1`, {
    headers: { cookie: adminCookie }
  });
  assert.equal(printablePdf.response.status, 200);
  assert.match(printablePdf.response.headers.get("content-disposition"), /^inline;/);
  assert.equal(printablePdf.response.headers.get("content-type"), "application/pdf");
  const certificatePage = await app.request(`/certificates/${certificate.id}`, {
    headers: { cookie: adminCookie }
  });
  assert.equal(certificatePage.response.status, 200);
  assert.match(certificatePage.text, new RegExp(`/certificates/${certificate.id}\\.pdf\\?print=1`));

  const verification = await app.request(`/verify/${encodeURIComponent(certificate.certificateNumber)}`);
  assert.equal(verification.response.status, 200);
  assert.match(verification.text, new RegExp(certificate.certificateNumber.replaceAll("/", "\\/")));
  assert.match(verification.text, /Alex Seafarer/);
  const missingVerification = await app.request("/verify/000000000%2F01%2F01%2F2000");
  assert.equal(missingVerification.response.status, 404);

  await app.waitFor(
    () => app.smtp.messages.some((message) => decodedSmtpText(message).includes(certificate.certificateNumber)),
    "Certificate email was not delivered to the SMTP fixture."
  );
  const certificateEmail = app.smtp.messages.find((message) => decodedSmtpText(message).includes(certificate.certificateNumber));
  assert.ok(smtpAttachmentNames(certificateEmail).some((name) => name.toLowerCase().endsWith(".pdf")));
  assert.ok(readFileSync(`${app.uploadsDir}/${app.readDb().users.find((user) => user.id === "user_student").photoUrl.replace("/uploads/", "")}`).length > 100);
});
